version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bb:55:52:6c:68:0e:90:15:69:ff:b3:1f:49:51:e6:8d"
      - checkout
      - run: npm ci
      - run: npx react-scripts build
      - run: git config --global user.email $GIT_EMAIL
      - run: git config --global user.name $GIT_USER
      - run: npx gh-pages -d build

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
